name: Android Build

on:
  push:
    branches:
      - feature/generacion-apk-actions
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle' 
          
      - name: Install Android SDK and Build Tools
        run: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
            mkdir -p $HOME/android-sdk/cmdline-tools
            unzip -q commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
            mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
            export ANDROID_HOME=$HOME/android-sdk
            export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/29.0.3:$PATH
            yes | sdkmanager --licenses
            sdkmanager "platform-tools" "build-tools;29.0.3" "platforms;android-33"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign App
        uses: ilharp/sign-android-release@v1.0.4
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Rename Signed APK
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/abc-call.apk

      - name: List all APKs
        run: find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: abc-call-apk
          path: ./app/build/outputs/apk/release/abc-call.apk